# Generated by Django 4.1.7 on 2023-07-20 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='scoial_linkedin',
            new_name='social_linkedin',
        ),
    ]
